apiVersion: v1
kind: ConfigMap
metadata:
  name: error-injector-cfm
data:
 nginx.conf: |-
    events {}
    http {
        server {
          listen 8080;
            location / {
                return 500;
            }
        }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: error-injector-deployment
spec:
  selector:
    matchLabels:
      app: error-injector-pod
  replicas: 1
  template:
    metadata:
      labels:
        app: error-injector-pod
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
      volumes:
        - name: nginx-config
          configMap:
            name: error-injector-cfm
