apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
spec:
  containers:
  - name: nginx-container
    image: nginx:alpine
    env:
    - name: myEnvVar
      value: "myEnvValue"
    livenessProbe:
      tcpSocket:
        port: 80
      initialDelaySeconds: 15
      periodSeconds: 20
    readinessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 10
    resources:
      requests:
        memory: "50Mi"
        cpu: "250m"
      limits:
        memory: "200Mi"
        cpu: "500m"
    ports:
    - containerPort: 80